version: "3"
services:
  # # User Service
  # rtarf-api-user-service:
  #   container_name: rtarf-api-user-service
  #   build: .
  #   restart: always
  #   hostname: rtarf-api-user-service
  #   networks:
  #     - backend
  #   links:
  #     - db

  # User DB
  rtarf-db-user:
    container_name: rtarf-db-user
    image: postgres
    restart: always
    ports:
      - "5403:5432"
    env_file:
      - ../.env.prod
    volumes:
      - ./.data/postgres_prod:/var/lib/postgresql/data
      - ./db/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge
