#!/bin/bash
set -e

PGPASSWORD=$POSTGRES_PASSWORD

psql -d "$POSTGRES_DB" -U "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_SERVICE_USER WITH PASSWORD '$POSTGRES_SERVICE_PASSWORD';
    CREATE DATABASE $POSTGRES_SERVICE_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_SERVICE_DB TO $POSTGRES_SERVICE_USER;
EOSQL